# Generated by Django 3.2.8 on 2021-10-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='', help_text='Crawled url', max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('port', models.PositiveSmallIntegerField(default=80, null=True)),
                ('port_specified', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('domain_specified', models.BooleanField(default=False)),
                ('domain_initial_dot', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=500, null=True)),
                ('path_specified', models.BooleanField(default=False)),
                ('secure', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(null=True)),
                ('discard', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('comment_url', models.URLField(default='', max_length=500, null=True)),
                ('rest', models.CharField(max_length=100, null=True)),
                ('rfc2109', models.BooleanField(default=False)),
                ('crawled_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=500, null=True)),
                ('links', models.PositiveSmallIntegerField(null=True)),
                ('metatype', models.TextField(null=True)),
            ],
        ),
    ]
